// server/routes/xmlMockData.ts
// Mock XML data for development and testing while API integration is refined

export const MOCK_GAMES_XML = `<?xml version="1.0" encoding="UTF-8"?>
<games>
  <game>
    <id>586657</id>
    <home>Tampa Bay Rays</home>
    <away>Boston Red Sox</away>
    <sport>Baseball</sport>
    <league>MLB</league>
    <startTime>2025-08-21T19:10:00Z</startTime>
    <status>scheduled</status>
    <homeScore>0</homeScore>
    <awayScore>0</awayScore>
  </game>
  <game>
    <id>586658</id>
    <home>New York Yankees</home>
    <away>Toronto Blue Jays</away>
    <sport>Baseball</sport>
    <league>MLB</league>
    <startTime>2025-08-21T19:05:00Z</startTime>
    <status>scheduled</status>
    <homeScore>0</homeScore>
    <awayScore>0</awayScore>
  </game>
  <game>
    <id>586659</id>
    <home>Los Angeles Lakers</home>
    <away>Golden State Warriors</away>
    <sport>Basketball</sport>
    <league>NBA</league>
    <startTime>2025-08-21T20:00:00Z</startTime>
    <status>scheduled</status>
    <homeScore>0</homeScore>
    <awayScore>0</awayScore>
  </game>
  <game>
    <id>586660</id>
    <home>Dallas Cowboys</home>
    <away>Green Bay Packers</away>
    <sport>Football</sport>
    <league>NFL</league>
    <startTime>2025-08-21T21:20:00Z</startTime>
    <status>scheduled</status>
    <homeScore>0</homeScore>
    <awayScore>0</awayScore>
  </game>
  <game>
    <id>586661</id>
    <home>Real Madrid</home>
    <away>Barcelona</away>
    <sport>Soccer</sport>
    <league>La Liga</league>
    <startTime>2025-08-21T18:00:00Z</startTime>
    <status>scheduled</status>
    <homeScore>0</homeScore>
    <awayScore>0</awayScore>
  </game>
</games>`;

export const MOCK_ODDS_XML = `<?xml version="1.0" encoding="UTF-8"?>
<odds>
  <odd>
    <book>DraftKings</book>
    <market>moneyline</market>
    <side>home</side>
    <odds>1.91</odds>
  </odd>
  <odd>
    <book>DraftKings</book>
    <market>moneyline</market>
    <side>away</side>
    <odds>1.95</odds>
  </odd>
  <odd>
    <book>FanDuel</book>
    <market>moneyline</market>
    <side>home</side>
    <odds>1.87</odds>
  </odd>
  <odd>
    <book>FanDuel</book>
    <market>moneyline</market>
    <side>away</side>
    <odds>1.99</odds>
  </odd>
  <odd>
    <book>BetMGM</book>
    <market>moneyline</market>
    <side>home</side>
    <odds>1.89</odds>
  </odd>
  <odd>
    <book>BetMGM</book>
    <market>moneyline</market>
    <side>away</side>
    <odds>1.97</odds>
  </odd>
  <odd>
    <book>Caesars</book>
    <market>moneyline</market>
    <side>home</side>
    <odds>1.93</odds>
  </odd>
  <odd>
    <book>Caesars</book>
    <market>moneyline</market>
    <side>away</side>
    <odds>1.93</odds>
  </odd>
  <odd>
    <book>DraftKings</book>
    <market>spread</market>
    <side>home</side>
    <line>-1.5</line>
    <odds>1.91</odds>
  </odd>
  <odd>
    <book>DraftKings</book>
    <market>spread</market>
    <side>away</side>
    <line>1.5</line>
    <odds>1.95</odds>
  </odd>
  <odd>
    <book>FanDuel</book>
    <market>spread</market>
    <side>home</side>
    <line>-1.5</line>
    <odds>1.87</odds>
  </odd>
  <odd>
    <book>FanDuel</book>
    <market>spread</market>
    <side>away</side>
    <line>1.5</line>
    <odds>1.99</odds>
  </odd>
  <odd>
    <book>DraftKings</book>
    <market>total</market>
    <side>over</side>
    <line>8.5</line>
    <odds>1.91</odds>
  </odd>
  <odd>
    <book>DraftKings</book>
    <market>total</market>
    <side>under</side>
    <line>8.5</line>
    <odds>1.95</odds>
  </odd>
  <odd>
    <book>FanDuel</book>
    <market>total</market>
    <side>over</side>
    <line>8.5</line>
    <odds>1.87</odds>
  </odd>
  <odd>
    <book>FanDuel</book>
    <market>total</market>
    <side>under</side>
    <line>8.5</line>
    <odds>1.99</odds>
  </odd>
  <odd>
    <book>BetMGM</book>
    <market>total</market>
    <side>over</side>
    <line>8.5</line>
    <odds>1.89</odds>
  </odd>
  <odd>
    <book>BetMGM</book>
    <market>total</market>
    <side>under</side>
    <line>8.5</line>
    <odds>1.97</odds>
  </odd>
  <odd>
    <book>Caesars</book>
    <market>total</market>
    <side>over</side>
    <line>8.5</line>
    <odds>1.93</odds>
  </odd>
  <odd>
    <book>Caesars</book>
    <market>total</market>
    <side>under</side>
    <line>8.5</line>
    <odds>1.93</odds>
  </odd>
</odds>`;